language: go

go:
- master

install:
- go get github.com/spf13/hugo

script:
- hugo
- echo 'aleiwu.com' > public/CNAME # declare CNAME

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: public
  on:
    branch: master